### PR TITLE
Python 3-ification

### PR DESCRIPTION
**Pull request by SimplicityGuy**
- Making the code run in `Python 3.6+`
- Reformatting per `black` formating tool

### CODE REVIEW

**Review by mbreemhaar — APPROVED** [review]

**Comment by SimplicityGuy** [comment]
@mbreemhaar Can you merge this PR, please?

**Comment by mbreemhaar** [comment]
I would if I could, but I am not the owner of this repo. @scaperot can you merge this?

**Comment by scaperot** [comment]
Hey, I'll try and take a look tomorrow night.  Thanks for ping!

**Comment by SimplicityGuy** [comment]
@scaperot Can you take a look at this PR? It gets the code up to current Python versions.

**Pull request merged**
